[project]
name = "wordle-info-theory"
version = "2.0.0"
description = "Optimizing Wordle gameplay by way of information theory"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scipy>=1.18.0",
    "scipy-stubs~=1.18.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=6.0.0",
    ]

[tool.pytest.ini_options]
pythonpath = ["."]  # Effectively replaces "python -m pytest"
testpaths = ["tests"]

# Specifies default cmd-line flags to prevent manual retyping
addopts = [
    "--cov=game_files.wordle_updated",
    "--cov-report=term-missing",
    "--cov-report=html"
]

[tool.coverage.run]
source = ["game_files.wordle_updated"]
omit = ["tests/*"]
